### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by spirosmastorakis** [01org/intel-sgx-ssl#2]
Hi, 

I tried to install the SGX SSL implementation by running the build_sgxssl.sh script, but the installation failed with the following error message: 

ar: creating libcrypto.a
ranlib libcrypto.a || echo Never mind.
cp: cannot create regular file ‘/home/spyros/Desktop/intel-sgx-ssl/package/lib64/release/libsgx_tsgxssl_crypto.a’: No such file or directory

When I modify the script to create the missing directories, it terminates successfully, however the SGX SSL libraries are not in the package/lib64/{debug|release} directories. Both directories are actually empty.

I ran the script as root, so there should not be any issues with the OS permissions.

My operating system is Ubuntu 14.04.1

Do you have any idea what goes wrong?

**Comment by bestcccc1232123** [comment]
The same happens to me as well! Indeed if I create the missing directories, I still get the error message:
cp: target '/home/netsec/Repository/intel-sgx-ssl/package/include/openssl/' is not a directory

Anybody has any idea how to solve it?

**Comment by haitaohuang** [comment]
Thanks for reporting this issue.
Both paths for include and lib should have been created before running the script (script should be fixed not assuming that.): package/lib64/{release|debug} and package/include/openssl
Note also those directories will be removed upon successful build and packaging files into a zip.

you can run "./build_sgxssl.sh no-clean" to leave the binaries in the package folder

**Comment by akryeem-INTC** [comment]
Fixed, missing directories will be automatically generated.
