### ISSUE TITLE
OpenSSL does not build reliably with 'make -j'

### ISSUE THREAD

**Issue by mechalas** [01org/intel-sgx-ssl#4]
OpenSSL has never reliably built with make -j. Support for parallel builds breaks on some platforms and not on others, and seems to break periodically all around. I was unable to compile 1.1.0e or 1.1.0f on Ubuntu 16.04 using a stock installation with the build script due to numerous errors. Removing the -j option fixes this.

Suggest you remove the -j option from make in your build script.

**Comment by akryeem-INTC** [comment]
Will consider removing this option
