### ISSUE TITLE
Build script failing for OpenSSL 1.0.2l

### ISSUE THREAD

**Issue by sgtpepperpt** [01org/intel-sgx-ssl#7]
Hey! Using the OpenSSL LTS 1.0.2l release doesn't work, the problem being with the ```make build_generated libcrypto.a``` command (target not found). However, the 1.0.2f seems to be working fine.

**Comment by akryeem-INTC** [comment]
Hi,
This SGXSSL version is built to work with OpenSSL 1.1.0 releases.
It wasn't checked or tested in 1.0.2 version.

**Comment by sgtpepperpt** [comment]
Maybe that could be added to the readme, so other users are aware of that? Thanks for your attention anyway
